django/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

django/inmoongram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

django/articles/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=250)
    image = models.ImageField(blank=True, upload_to='media')
    image_description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    is_public = models.BooleanField(default=True)

django/articles/forms.py
from django import forms
from .models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = '__all__'
        widgets = {
            'title': forms.TextInput(attrs={'placeholder' : '제목을 입력하시오'}),
            'content' : forms.TextInput(attrs={'placeholder' : '내용을 입력하시오'}),
            'image_description': forms.Textarea(attrs={'placeholder' : '이미지 설명을 입력하시오'})
        }

django/articles/views.py
from django.shortcuts import render,redirect
from .models import Article
from .forms import ArticleForm
# Create your views here.
def index(request):
    articles = Article.objects.all()
    context = {
        'articles':articles,
    }
    return render(request, 'articles/index.html', context)

def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save()
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm()
    context = {
        'form':form,
    }
    return render(request, 'articles/create.html', context)

def detail(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article':article,
    }
    return render(request, 'articles/detail.html', context)

def update(request, pk):
    article = Article.objects.get(pk=pk)
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES, instance=article)
        if form.is_valid():
            article = form.save()
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm(instance=article)
    context = {
        'article':article,
        'form':form,
    }
    return render(request, 'articles/update.html', context)

def delete(request, pk):
    if request.method == 'POST':
        article = Article.objects.get(pk=pk)
        article.delete()
        return redirect('articles:index')
    else:
        return redirect('articles.index')

django/articles/templates/articles/create.html
{% extends 'base.html' %}
{% block content %}
<h1>게시글 생성 페이지</h1>
  <form action="{% url 'articles:create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p  }}
    <input type="submit" value="CREATE">
  </form>
  <p><a href="{% url 'articles:index' %}">[BACK]</a></p>
{% endblock content %}

django/articles/templates/articles/detail.html
{% extends 'base.html' %}
{% block content %}
  <h1>게시글 상세 페이지</h1>
  <p>{{  article.pk  }}번 게시글 | {{  article.content }}</p>
  <p>작성 시간 : {{  article.created_at  }}</p>
  {% if article.image %}
    <img src="{{  article.image.url  }}" alt="image">
  {% endif %}
  <hr>
  <p>{{  article.title  }}</p>
  <p><a href="{% url 'articles:update' article.pk%}" >[UPDATE]</a></p>
  <form action="{% url 'articles:delete' article.pk%}" method="POST">
    {% csrf_token %}
    <input type="submit" value="DELETE">
  </form>
  <a href="{% url 'articles:index' %}">[BACK]</a>
{% endblock content %}

django/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>나만의 SNS 서비스</h1>
  <p><a href="{% url 'articles:create' %}">[CREATE]</a></p>
  {% for article in articles %}
  {% if article.image %}
    <img src="{{  article.image.url  }}" alt="image">
  {% endif %}
    <p><a href="{% url 'articles:detail' article.pk%}">{{  article.title  }}</a></p>
    <hr>
  {% endfor %}
{% endblock content %}

django/articles/templates/articles/update.html
{% extends 'base.html' %}
{% block content %}
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{  form.as_p  }}
    <input type="submit" value="UPDATE">
  </form>
  <p><a href="{% url 'articles:detail' article.pk%}">[BACK]</a></p>
{% endblock content %}

django/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  {% block content %}
    
  {% endblock content %}
</body>
</html>